import { expo } from "@better-auth/expo";
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { admin } from "better-auth/plugins";

import { generateAppleClientSecret } from "./apple";
import type { CreateAuthOptions } from "./types";

export type { CreateAuthOptions } from "./types";

/**
 * Build the Boccone Better Auth instance.
 *
 * Authorization model: Better Auth's admin plugin with the two default roles
 * (`user`, `admin`). Role is stored on the user row and enforced server-side;
 * there is deliberately no richer RBAC until the product needs it.
 *
 * Note: the Expo server plugin is always enabled — it is required for native
 * flows and is inert for browser clients.
 */
export function createAuth(options: CreateAuthOptions) {
  const mobileScheme = options.mobileScheme ?? "boccone";
  const apple = options.apple;

  const trustedOrigins = [
    ...options.trustedOrigins,
    `${mobileScheme}://`,
    // Apple's token endpoint participates in the OAuth flow.
    ...(apple ? ["https://appleid.apple.com"] : []),
    ...(options.isProduction
      ? []
      : [
          // Expo Go / dev-client deep links with local machine IPs.
          "exp://",
          "exp://**",
          "exp://192.168.*.*:*/**",
        ]),
  ];

  return betterAuth({
    database: drizzleAdapter(options.db, {
      provider: "pg",
    }),
    advanced: {
      database: {
        // Requires relations in the Drizzle schema (generated by the auth CLI).
        joins: true,
      },
    },
    secret: options.secret,
    baseURL: options.baseURL,
    trustedOrigins,
    emailAndPassword: {
      enabled: true,
      revokeSessionsOnPasswordReset: true,
      sendResetPassword: async ({ user, url }) => {
        await options.sendResetPasswordEmail({ to: user.email, resetUrl: url });
      },
    },
    socialProviders: {
      ...(options.google
        ? {
            google: {
              clientId: options.google.clientId,
              clientSecret: options.google.clientSecret,
            },
          }
        : {}),
      ...(apple
        ? {
            apple: async () => ({
              clientId: apple.clientId,
              clientSecret: await generateAppleClientSecret(apple),
              // Needed for native ID-token sign-in, where Apple audiences the
              // App ID (bundle identifier) instead of the Services ID.
              appBundleIdentifier: apple.bundleId,
            }),
          }
        : {}),
    },
    plugins: [
      admin({
        // Smallest viable authorization model: plain users and admins.
        defaultRole: "user",
      }),
      expo(),
    ],
    rateLimit: {
      enabled: options.rateLimitEnabled ?? true,
      window: 60,
      max: 100,
    },
  });
}
